export const kwsIS = [
  ["Revenue", "sa"],
  ["Sales per Share", "sps"],
  ["- Growth Rate (%)", "saG"],
  ["Cost of Sales", "cogo"],
  ["Gross Profit", "gpr"],
  ["- Gross Margin (%)", "gprM"],
  ["SG&A Expenses", "sgaad"],
  ["R&D Expenses", "rade"],
  ["Other Operating Expenses", "ooex"],
  ["Operating Income", "oin"],
  ["- Operating Margin (%)", "oinM"],
  ["Interest Expense", "ex"],
  ["Interest Income", "in"],
  ["Other Financials", "oiex"],
  ["Net Financials", "tfin"],
  ["Pre-Tax Income", "pin"],
  ["- Pre-Tax Margin (%)", "pinM"],
  ["Tax Expense", "ita"],
  ["- Tax Rate (%)", "taxR"],
  ["Net Income", "nin"],
  ["- Net Margin (%)", "ninM"],
  ["Mezzanine Equity expenses", "min"],
  ["Net Income for Shareholders", "nish"],
  ["Earnings per Share - Basic", "eba"],
  ["Earnings per Share - Diluted", "edi"],
  ["Number of shares - Basic", "bsou"],
  ["Number of shares - Diluted", "dsou"],
  ["EBITDA", "eb"],
  ["- EBITDA Margin (%)", "ebM"],
];

export const kwsBS = [
  ["Cash & Cash Equivalents", "caceq"],
  ["Short-Term Investments", "ostin"],
  ["Accounts Receivable", "are"],
  ["Other Receivables", "ore"],
  ["Inventory", "in"],
  ["Other Current Assets", "oca2"],
  ["Total Current Assets", "tcas"],
  ["PP&E, Gross", "ppeG"],
  ["Acummulated Depreciation", "ade"],
  ["PP&E, Net", "ppeN"],
  ["Goodwill", "go"],
  ["Intangible Assets", "ias"],
  ["Long-Term Investments", "ltiN"],
  ["Other Non-current Assets", "oncas"],
  ["Total Non-current Assets", "tncas"],
  ["Total Assets", "tas"],
  ["- Return on Assets (%)", "roa"],
  ["Accounts Payable", "apa"],
  ["Accrued Expenses", "aex"],
  ["Current Debt", "std"],
  ["Deferred Revenue", "dre"],
  ["Other Current Liabilities", "ocl2"],
  ["Total Current Liabilities", "tcli"],
  ["Long-Term Debt", "ltde"],
  ["Provisions", "prvS"],
  ["Other Long-Term Liabilities", "oncli"],
  ["Total Non-Current Liabilities", "tncli"],
  ["Total Liabilities", "tli"],
  ["Common Shares & APIC", "cst"],
  ["Retained Earnings", "rea"],
  ["Other Comprehensive Income", "oseq"],
  ["Treasury Shares", "tst"],
  ["Total Shareholders Equity", "tseq"],
  ["Book Value per Share", "bvps"],
  ["- Return on Equity (%)", "roe"],
  ["Minority Interests", "min"],
  ["Total Liabilities + Equity", "tas"],
  ["Capital Employed", "cptE"],
  ["- Return on Capital Employed (%)", "roce"],
  ["Tangible Capital Employed", "cptT"],
  ["- Return on Tangible CE (%)", "rotce"],
  ["Tangible Assets", "tngB"],
  ["- Return on Tangible Assets (%)", "rota"],
  ["Total Debt", "dbtT"],
  ["Net Debt", "dbtN"],
  ["Working Capital", "wcpT"],
];

export const kwsCF = [
  ["Net Income", "ninCF"],
  ["Depreciation & Amortization", "de"],
  ["Stock-Based Compensation", "sbco"],
  ["Deferred Income Taxes", "dta"],
  ["Other Non-Cash Adjustments", "oncit"],
  ["Total Non-Cash Adjustments", "tncA"],
  ["Accounts Payable", "apa"],
  ["Accounts Receivable", "are"],
  ["Other Working Capital Movements", "oali"],
  ["Total Working Capital Movements", "wcmV"],
  ["Operating Cash Flow", "ocfl"],
  ["- OCF Margin (%)", "ocflMg"],
  ["Capital Expenditures", "cex"],
  ["- Capex / D&A (%)", "cpxR"],
  ["Free Cash Flow", "fcfl"],
  ["Acquisitions & Intangibles", "nac"],
  ["Purchase of Investments", "poin"],
  ["Sale of Investments", "soin"],
  ["Investing Cash Flow", "icfl"],
  ["Long-Term Debt Issuance", "ltdis"],
  ["Long-Term Debt Payments", "ltdpa"],
  ["Delta Short-Term Debt", "stdis"],
  ["Dividend Payments", "cdi"],
  ["Share Buyback", "csre"],
  ["Common Share Issuance ", "csis"],
  ["Other Financing Activities", "ofch"],
  ["Financing Cash Flow", "ficfl"],
  ["Net Cash Flow", "ncfl"],
  ["Interest Paid", "ipa"],
  ["Income Taxes Paid", "itpa"],
];

export const kwsFR = [
  ["Liquidity Ratios", "title"],
  ["Current Ratio", "cr"],
  ["Quick Ratio", "qr"],
  ["Cash Ratio", "caR"],
  ["Indebtness Ratios", "title"],
  ["Liabilities / Assets", "lta"],
  ["Debt / Equity", "dte"],
  ["Debt / EBITDA", "dteb"],
  ["Interest Coverage", "ic"],
  ["Leverage Ratio", "lev"],
  ["Turnover Ratios", "title"],
  ["Asset Turnover", "ast"],
  ["PP&E Turnover", "ppet"],
  ["Receivables Turnover", "rt"],
  ["Inventory Turnover", "invt"],
  ["Days", "title"],
  ["Days Sales Outstanding", "dso"],
  ["Days Inventories Outstanding", "dio"],
  ["Days Payables Outstanding", "dpo"],

  ["ROE - Du Pont"],
  ["Asset Turnover", "ast"],
  ["Leverage Ratio", "lev"],
  ["- Net Margin - Shareholders (%)", "nisM"],
  ["Return on Equity (%)", "roe"],
  ["CF - Quality of Income", "title"],
  ["QOI - Operating Cash Flow", "qoiO"],
  ["QOI - Free Cash Flow", "qoiF"],
  ["CF - Debt Coverages", "title"],
  ["Total Debt Coverage", "tdc"],
  ["Short-Term Debt Coverage", "stdc"],
  ["Debt Repayment Coverage", "drc"],
  ["CF - Sh. Distribution Coverage", "title"],
  ["Dividend Payments Coverage", "divc"],
  ["Share Repurchase Coverage", "csrc"],
  ["Total Shareholders Distribution", "tsdc"],
];

export const kwsPS = [
  ["Decreased Leverage", "pdl"],
  ["Higher Current Ratio", "pcr"],
  ["No Shares Issued", "psh"],
  ["Total Liquidity & Leverage", "ptl"],
  ["Higher Operating Margin", "pom"],
  ["Higher Asset Turnover", "pat"],
  ["Total Operating Efficiency", "pef"],
  ["Positive Net Income", "pni"],
  ["Positive ROA", "pro"],
  ["Positive OCF", "poc"],
  ["Positive QOI", "pqo"],
  ["Total Profitability", "ppr"],
  ["Total Piotroski Score", "pts"],
];
